version: "3.3"
services:
 web:
   build:
    context: ./requirements/nginx/
   ports:
     - "443:443"
   volumes:
    - wordpress:/var/www/html

 wordpress:
  build:
   context: ./requirements/wordpress
  restart: always
  ports:
    - "9000:9000"
  volumes:
    - wordpress:/var/www/html

volumes:
  wordpress: