version: "3.3"
services:
 web:
   build:
    context: ./requirements/nginx/
   image: nginx
   ports:
     - "443:443"
   volumes:
    - /media/sf_inception/wp-files:/var/www/html
   links:
    - wordpress

 wordpress:
  build:
   context: ./requirements/wordpress
  image: wordpress
  restart: always
  ports:
    - "9000:9000"
  volumes:
    - /media/sf_inception/wp-files:/var/www/html