version: "3.3"
services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    restart: always
    volumes:
      - wp_db:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - wp_db

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    image: wordpress
    volumes:
      - wp-files:/var/www/html
    env_file:
      - .env
    networks:
      - wp_web
      - wp_db
    restart: always

  nginx:
    build:
      context: ./requirements/nginx/
    image: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/html
    networks:
      - wp_web

networks:
  wp_db:
  wp_web:

volumes:
  wp-files:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/viroques/data/wp-files

  wp_db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/viroques/data/db